### ISSUE TITLE
Change wording "split" to "bootstrap_samples"

### ISSUE THREAD

**Issue by danielmlow** [nipype/pydra-ml#17]
Just a thought: 

Maybe people not used to using bootstrapping will think the pipeline is doing k-fold and will set `n_splits` to 5/7/10 which would lead to too few test sets for bootstrapping. "Split" sounds like k-fold non overlapping split, so I think the word "n_bootstrap_samples" will be more obvious. 

If both k-fold and bootstrapping are available, then the word could be "n_samples"

**Comment by satra** [comment]
`splits` comes straight from the shufflesplit keywords. i would not change this as most people using scikit-learn understand what this is.
