### ISSUE TITLE
Test pydraml on different Operating Systems

### ISSUE THREAD

**Issue by nicolocin** [nipype/pydra-ml#23]

**Comment by satra** [comment]
this came up yesterday. the timestamp format being used when saving files doesn't work on windows because it contains `:` character

**Comment by tashrifbillah** [comment]
Hi @satra , do you need someone to work on this during BrainHack?
cc @djarecka

**Comment by djarecka** [comment]
@tashrifbillah - sure! you can test locally, or you can also add new os to the tests via Github Action: https://github.com/nipype/pydra-ml/blob/master/.github/workflows/pythonpackage.yml

**Comment by satra** [comment]
closed via #26
