### ISSUE TITLE
use predict_proba() when metric is roc_auc_score

### ISSUE THREAD

**Issue by danielmlow** [nipype/pydra-ml#56]
pydra-ml currently computes ROC AUC with .predict(X_test), which tends to give lower values of ROC AUC (a more stepwise curve) than the proper way of using probabilities for class 1 obtained through predict_proba(X_test):

https://github.com/nipype/pydra-ml/blob/8fd4536de3a5431219f924897c09aa905c3bc89a/pydra_ml/tasks.py#L102

So this could be added to this section, although not sure predict_proba() is available for all algorithms:
```
y_proba = pipe.predict_proba(X_test)       # Get predicted probabilities
y_proba_1 = y_proba[:,1]
y_pred = np.argmax(y_proba, axis=1)
```

Maybe add metrics as an argument to the train_test_kernel():
https://github.com/nipype/pydra-ml/blob/8fd4536de3a5431219f924897c09aa905c3bc89a/pydra_ml/tasks.py#L54

And then add a condition here:
https://github.com/nipype/pydra-ml/blob/8fd4536de3a5431219f924897c09aa905c3bc89a/pydra_ml/tasks.py#L102
```
if metric == roc_auc_score:
    y_pred = pipe.predict_proba(X_test)       # Get predicted probabilities
    y_pred = y_pred[:,1]
else:
    y_pred = pipe.predict(X[test_index])     # Use 0.5 threshold
```

The issue is that models I think can currently take multiple metrics. So maybe you need to save probabilities if roc_auc_score is one of the metrics but also always save predict() output like this:
```
if metric == roc_auc_score:
    y_proba = pipe.predict_proba(X_test)       # Get predicted probabilities
    y_pred = y_proba[:,1]
else:
    y_pred = pipe.predict(X[test_index])     # Use 0.5 threshold
```

But then you need to change which output it is indexing here:
https://github.com/nipype/pydra-ml/blob/8fd4536de3a5431219f924897c09aa905c3bc89a/pydra_ml/tasks.py#L117

**Comment by satra** [comment]
indeed one penalizes roc_auc_score by using predict for that metric. we could indeed save both if available and use it for that metric. i think `roc_auc_score` is the only metric that can take probability scores (besides the curve generators).  

saving both and using it for roc_auc_score is the easier route at this point in pydra-ml.

**Comment by satra** [comment]
sending a PR soon to allow this.
